-- ## Problem 5
-- 
-- Enable auto increment on the primary key in the CUSTOMER table.
-- The values should start with 2000.
-- 

/* YOUR SOLUTION HERE */
ALTER TABLE INVOICE DROP FOREIGN KEY invoice_ibfk_1;
ALTER TABLE CUSTOMER MODIFY CUST_NUM INT NOT NULL AUTO_INCREMENT;
ALTER TABLE CUSTOMER AUTO_INCREMENT=2000;
ALTER TABLE INVOICE
ADD CONSTRAINT invoice_ibfk_1
FOREIGN KEY (CUST_NUM) REFERENCES CUSTOMER(CUST_NUM);
